name: Gunshell
version: '${project.version}'
main: com.jazzkuh.gunshell.GunshellPlugin
api-version: 1.13
authors: [Jazzkuh]
softdepend: [WorldGuard]
commands:
  gunshell:
    aliases: [gs, gun, weapons, weapon, mtwapens, mtwapen]
