name: Lancaster
version: '${project.version}-${git.commit.id.describe-short}'
main: com.jazzkuh.lancaster.LancasterPlugin
api-version: 1.13
authors: [Jazzkuh]
depend: [Server-Core]
softdepend: [WorldGuard]
commands:
  lancaster:
    aliases: [lc]
