name: MTWapens
version: '3.6'
website: 'https://www.spigotmc.org/resources/76350/'
main: com.jazzkuh.gunshell.GunshellPlugin
api-version: 1.13
description: "Add guns, melee weapons and throwables to your Minecraft server."
authors: [Jazzkuh, Esmaybe]
softdepend: [WorldGuard]
commands:
  mtwapen:
    aliases: [weapons, weapon, mtwapen]